name: "✨Feat"
description: "새로운 기능 또는 명세가 있나요?"
title: "[✨Feat]"
labels: ["feat"]

body:
  - type: textarea
    attributes:
      label: 📄 Describe
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ Tasks
      description: 해야 하는 일에 대한 Tasks를 작성해 주세요.
      placeholder: 최대한 세분화해서 적어주세요!
      value: |
        - [ ] API 엔드포인트 설계
        - [ ] 서비스 로직 구현
        - [ ] 테스트 코드 작성
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 More
      description: 더 하고 싶은 말이 있다면 작성해 주세요.
