name: Mongle CD Pipeline

on:
  workflow_dispatch:
    inputs:
      target:
        description: '배포할 환경 선택 (dev / prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target == 'prod' && 'main' || 'develop' }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mongle-app:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mongle-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/mongle"

      - name: Run Docker Compose on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/mongle
            echo "${{ secrets.ENV_FILE }}" > .env
            export DOCKER_IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/mongle-app"
            export IMAGE_TAG="${{ github.sha }}"
            docker pull $DOCKER_IMAGE_NAME:$IMAGE_TAG
            docker compose --env-file .env pull
            docker compose --env-file .env down
            docker compose --env-file .env up -d